import type { FeedPost } from '../types/content.types'

export const feedPosts: FeedPost[] = [
  {
    id: 'ai-for-business-practical-adoption',
    title: 'AI for Business: Practical Adoption',
    category: 'AI for Business',
    date: '2026-06-03',
    readTime: '4 min',
    sourceLabel: 'Founder Notes',
    sourceUrl: '#',
    summary: 'Practical advice for applying AI in operations without overpromising automation outcomes.',
    jonathanTake: 'AI should augment human workflows, not replace them; start with decision support and verification.',
    businessImpact: 'Helps teams adopt AI in a controlled, measurable way that reduces implementation risk.',
    relatedProjectId: 'os3-dash',
    tags: ['AI', 'business', 'adoption'],
    status: 'Published'
  },
  {
    id: 'systems-thinking-why-dashboards-fail',
    title: 'Systems Thinking: Why Dashboards Fail',
    category: 'Systems Thinking',
    date: '2026-06-03',
    readTime: '5 min',
    sourceLabel: 'Systems Journal',
    sourceUrl: '#',
    summary: 'A brief on the common dashboard failure modes and how to build a command layer that actually drives decisions.',
    jonathanTake: 'Dashboards fail when they are built for show instead of action; focus on workflow outcomes instead of vanity metrics.',
    businessImpact: 'Encourages product teams to design dashboards that surface the right decisions at the right time.',
    relatedProjectId: 'os3-dash',
    tags: ['dashboards', 'systems', 'decision-making'],
    status: 'Published'
  },
  {
    id: 'founder-notes-building-under-pressure',
    title: 'Founder Notes: Building Under Pressure',
    category: 'Founder Notes',
    date: '2026-06-03',
    readTime: '3 min',
    sourceLabel: 'Founder Journal',
    sourceUrl: '#',
    summary: 'A founder note on staying grounded, reducing noise, and keeping the mission clear during high-stakes work.',
    jonathanTake: 'The best work comes from calm systems when pressure is present; structure the environment, not just the effort.',
    businessImpact: 'Supports teams in maintaining resilience and clarity amid fast-moving product cycles.',
    relatedProjectId: 'jb3-daily',
    tags: ['founder', 'pressure', 'resilience'],
    status: 'Published'
  },
  {
    id: 'product-update-os3-dash-direction',
    title: 'Product Update: OS³ Dash Direction',
    category: 'Product Update',
    date: '2026-06-03',
    readTime: '4 min',
    sourceLabel: 'Update Brief',
    sourceUrl: '#',
    summary: 'An update on the direction, design goals, and business role of OS³ Dash in the JB³Ai ecosystem.',
    jonathanTake: 'OS³ Dash is about connecting executive signal to operational action, not just visualizing data for its own sake.',
    businessImpact: 'Clarifies roadmap priorities for the command layer and how it supports growth-ready business operations.',
    relatedProjectId: 'os3-dash',
    tags: ['product', 'roadmap', 'update'],
    status: 'Published'
  },
  {
    id: 'gtr3-journal-the-third-rise',
    title: 'GTR3 Journal: The Third Rise',
    category: 'GTR3 Journal',
    date: '2026-06-03',
    readTime: '5 min',
    sourceLabel: 'GTR3 Notes',
    sourceUrl: '#',
    summary: 'A journal entry exploring the third rise story, narrative framing, and the founder’s long-term vision.',
    jonathanTake: 'Story is the frame around systems; the third rise is both a metaphor and an operating discipline.',
    businessImpact: 'Helps investors and partners understand the cultural and narrative context behind the operating system design.',
    relatedProjectId: 'gtr3',
    tags: ['GTR3', 'story', 'journal'],
    status: 'Published'
  },
  {
    id: 'security-signal-verification-before-trust',
    title: 'Security Signal: Verification Before Trust',
    category: 'Security Signal',
    date: '2026-06-03',
    readTime: '3 min',
    sourceLabel: 'Security Notes',
    sourceUrl: '#',
    summary: 'A security signal post about why verification must come before trust in business systems and media channels.',
    jonathanTake: 'Trust is earned through verifiable signal; don’t let stories outpace proof in an OS context.',
    businessImpact: 'Supports confidence in the public feed by emphasizing rigorous verification over hype.',
    relatedProjectId: 'public-feed',
    tags: ['security', 'verification', 'trust'],
    status: 'Published'
  }
]
