import type { SocialLink } from '../types/content.types'

export const socialLinks: SocialLink[] = [
  {
    id: 'book-call',
    label: 'Book a Call',
    group: 'Primary Contact',
    platform: 'Scheduler',
    purpose: 'Request a discovery or executive call with Jonathan Blackburn.',
    url: '#',
    visibility: 'Public',
    priority: 1,
    iconName: 'PhoneCall',
    cautionNote: 'Placeholder booking URL; actual scheduling route is pending.'
  },
  {
    id: 'email-jonathan',
    label: 'Email Jonathan',
    group: 'Primary Contact',
    platform: 'Email',
    purpose: 'Send a direct email to discuss projects, proof, or collaboration.',
    url: '#',
    visibility: 'Public',
    priority: 2,
    iconName: 'Mail',
    cautionNote: 'Placeholder email link; actual address is not published here.'
  },
  {
    id: 'linkedin',
    label: 'LinkedIn',
    group: 'Personal Profiles',
    platform: 'LinkedIn',
    purpose: 'Professional profile and verification for founder activities.',
    url: '#',
    visibility: 'Public',
    priority: 3,
    iconName: 'Linkedin',
    cautionNote: 'Placeholder LinkedIn URL.'
  },
  {
    id: 'github',
    label: 'GitHub',
    group: 'Personal Profiles',
    platform: 'GitHub',
    purpose: 'Code samples, projects, and technology proof points.',
    url: '#',
    visibility: 'Public',
    priority: 4,
    iconName: 'Github',
    cautionNote: 'Placeholder GitHub profile URL.'
  },
  {
    id: 'jb3ai-website',
    label: 'JB³Ai Website',
    group: 'JB³Ai Channels',
    platform: 'Website',
    purpose: 'Company-level proof, technology notes, and channel overview.',
    url: '#',
    visibility: 'Public',
    priority: 5,
    iconName: 'Globe',
    cautionNote: 'Placeholder company website URL.'
  },
  {
    id: 'youtube',
    label: 'YouTube',
    group: 'Media Channels',
    platform: 'YouTube',
    purpose: 'Media content, founder briefings, and product video previews.',
    url: '#',
    visibility: 'Public',
    priority: 6,
    iconName: 'Youtube',
    cautionNote: 'Placeholder YouTube channel link.'
  },
  {
    id: 'whatsapp-channel',
    label: 'WhatsApp Channel',
    group: 'JB³Ai Channels',
    platform: 'WhatsApp',
    purpose: 'Channel updates and community contact in a private preview layer.',
    url: '#',
    visibility: 'Preview',
    priority: 7,
    iconName: 'MessageCircle',
    cautionNote: 'Placeholder WhatsApp channel invite.'
  },
  {
    id: 'instagram',
    label: 'Instagram',
    group: 'Media Channels',
    platform: 'Instagram',
    purpose: 'Visual updates, story highlights, and creative proof content.',
    url: '#',
    visibility: 'Preview',
    priority: 8,
    iconName: 'Instagram',
    cautionNote: 'Placeholder Instagram profile link.'
  },
  {
    id: 'facebook',
    label: 'Facebook',
    group: 'Media Channels',
    platform: 'Facebook',
    purpose: 'Community updates and event proof in a broad channel.',
    url: '#',
    visibility: 'Preview',
    priority: 9,
    iconName: 'Facebook',
    cautionNote: 'Placeholder Facebook page link.'
  },
  {
    id: 'x',
    label: 'X',
    group: 'Media Channels',
    platform: 'X',
    purpose: 'Short updates, commentary, and public channel signals.',
    url: '#',
    visibility: 'Preview',
    priority: 10,
    iconName: 'X',
    cautionNote: 'Placeholder X (Twitter) profile link.'
  },
  {
    id: 'tiktok',
    label: 'TikTok',
    group: 'Media Channels',
    platform: 'TikTok',
    purpose: 'Short-form story content and creative signal proof.',
    url: '#',
    visibility: 'Preview',
    priority: 11,
    iconName: 'Video',
    cautionNote: 'Placeholder TikTok profile link.'
  },
  {
    id: 'substack',
    label: 'Substack',
    group: 'Media Channels',
    platform: 'Substack',
    purpose: 'Writing and long-form updates for the OS story.',
    url: '#',
    visibility: 'Preview',
    priority: 12,
    iconName: 'BookOpen',
    cautionNote: 'Placeholder Substack link.'
  },
  {
    id: 'medium',
    label: 'Medium',
    group: 'Media Channels',
    platform: 'Medium',
    purpose: 'Essays, narrative proof, and systems thinking writing.',
    url: '#',
    visibility: 'Preview',
    priority: 13,
    iconName: 'Newspaper',
    cautionNote: 'Placeholder Medium profile link.'
  },
  {
    id: 'reddit',
    label: 'Reddit',
    group: 'Media Channels',
    platform: 'Reddit',
    purpose: 'Community discussion and trusted proof channels.',
    url: '#',
    visibility: 'Preview',
    priority: 14,
    iconName: 'MessageSquare',
    cautionNote: 'Placeholder Reddit community link.'
  },
  {
    id: 'imed-proof',
    label: 'Historical iMED Proof',
    group: 'Historical Proof',
    platform: 'Archive',
    purpose: 'Historic proof and reference for the iMED recovery layer.',
    url: '#',
    visibility: 'Preview',
    priority: 15,
    iconName: 'ShieldCheck',
    cautionNote: 'Placeholder historical proof record.'
  }
]
